### ISSUE TITLE
Erroneous reporting of titles available on a provider

### ISSUE THREAD

**Issue by davidfells** [haijeploeg/excludarr#61]
**Describe the bug**
When I run `excludarr radarr exclude`, the output shows titles available on Disney Plus that are not, in fact, available - such as Alien or Aliens.

**To Reproduce**
1. `excludarr radarr exclude -a delete -d e`
2. There are many - Alien, Aliens, Road to Perdition, the list goes on
3. Config here: https://gist.github.com/davidfells/c8edcd45dcf6d616e6b61290b080fcf1

**Expected behavior**
Expect a list where titles are in fact available on the indicated provider

**Versions**
1. OS Version: Debian 11
3. Excludarr version: 1.0.6
4. Python version: 3.9.2

**Debug logging**
To debug the problem further, we need to know exactly what went wrong. Therefor we ask you to run the command in debug mode. You can achieve this by appending the `--debug` flag after the base command `excludarr`. e.g. `excludarr --debug sonarr exclude -a delete -d -e`.

If the output is too long, please paste the output to pastebin or github gist and link it in this issue.

Output here: https://gist.github.com/davidfells/2ad6f71da2518459d733439dee9ac74a

**Additional context**

**Comment by haijeploeg** [comment]
Hi David, 

Thanks for reporting your issue! From what I can tell your Github profiles states that you live in the United States, correct? I see in your linked configuration file that you are using the `en_NL` locale. If you change this to `en_US` you should get the correct results for your country.

Disney Plus in the US differs from the database in NL, because of the licenses. So one movie can be streaming on Disney, Netflix etc. in one country, but not in another. Configuring the `locale` setting in the configfile properly should fix this.

Can you test this and report back the results?
