### ISSUE TITLE
can we please add paramount plus to the streaming providers list?

### ISSUE THREAD

**Issue by EdeAbreu23** [haijeploeg/excludarr#71]
**Is your feature request related to a problem? Please describe.**
it is not a problem, it is me asking for a new streaming provider to be included

**Describe the solution you'd like**
be able to also include paramount plus movies/tv shows to exclude

**Describe alternatives you've considered**
manually look for movies and tv shows that are present in paramount plus and remove them

**Additional context**
nothing

**Comment by haijeploeg** [comment]
You can use the `providers list` command, that will list all available providers. If it is not in the list, I cannot add it, since Justwatch is returning this information.

I have taken the development of excludarr on a pause for a while. I am aware of several issues in excludarr and I tend to fix it by creating a Web UI. Where users can control excludarr within an web interface. All the present features will be in there including some new features! I have started the development this week, but it will take some time, I hope to release it before christmas :) PS. I am replying with this message on every issue to make everyone aware.
